# node image version
FROM node:18

# Container directory
RUN mkdir -p /user/src/Highschool_App

# Project path as a work directory
WORKDIR /usr/src/Highschool_App

# Copy package.json
COPY package.json ./

# Run command
RUN npm install -g typescript

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Port
EXPOSE 3000

# CMD command
CMD npm run dev
# CMD ["npm", "run", "dev"] 